### ISSUE TITLE
[Issue] Error logs cause not playing music, and maybe not support `FixCameraResolution` made by Rumi (framerate drop)

### ISSUE THREAD

**Issue by CoolLKKPS** [Ssencipe/Overhaul_Moons#4]
@Ssencipe hey so, i confirmed this issue
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
LevelMusicLib.Patches.CustomMusicTrigger.ChooseWeightedClip (NewMusicEntry[] Musics) (at ./Patches/CustomMusicTrigger.cs:91)
LevelMusicLib.Patches.CustomMusicTrigger.PlayCustomMusic (LevelMusicLib.Scripts.CustomLevelMusic CustomMusicObject, UnityEngine.AudioSource MusicSource, System.Boolean EveningMusic) (at ./Patches/CustomMusicTrigger.cs:68)
LevelMusicLib.Patches.CustomMusicTrigger.PlayTimeMusicDelayedPatch (TimeOfDay __instance) (at ./Patches/CustomMusicTrigger.cs:38)
(wrapper dynamic-method) TimeOfDay.DMD<TimeOfDay::PlayTimeMusicDelayed>(TimeOfDay,UnityEngine.AudioClip,single,bool)
TimeOfDay.PlayerSeesNewTimeOfDay () (at <d491ed1d4cc34874a2498af41192fe04>:IL_005A)
TimeOfDay.TimeOfDayEvents () (at <d491ed1d4cc34874a2498af41192fe04>:IL_00B9)
TimeOfDay.Update () (at <d491ed1d4cc34874a2498af41192fe04>:IL_0121)

using `LethalLevelLoaderAOORE_Fix v1.3.10 by Skeletonek`

**Comment by CoolLKKPS** [comment]
another issue is the framerate drop, with no other mods i can play with about 70 FPS (my rig is old btw), but after playing `myc` planet, my framerate are drop to about 20 FPS, but i did install `FixCameraResolution` to remove some fogs, can u investigate that?
i did not increase the in-game resolution

**Comment by Ssencipe** [comment]
Looking into it. Can't say when due to having inconsistent free time currently, but it's on the list now.

**Comment by Ssencipe** [comment]
Fixed the music related error. Did a couple things for FPS but there's not much that can be done at base without going out of scope of the project. Going to investigate the camera mod next.

**Comment by Ssencipe** [comment]
Not getting explicit errors with the mod, nor is it affecting things on my end.  The moon is one of the fancier ones in regards to how performance would handle it, but I can't really improve performance without either overhauling the entire project or reducing quality for other users who do enjoy it at its current state. Best I can suggest is utilizing other performance mods such as AsyncLogger or CullFactory to mitigate some of the effects. If you are using FixCameraResolution for just removing fog you could try another fog remover mod, and if you need it for resolution you could try LCUltrawideCommunity instead. Otherwise That's about all I can offer at this time.

**Comment by CoolLKKPS** [comment]
nice, ok thx!
